stages:
  - CompressingVanilla
  - CompressingModed
  - Packing
  - Packaging
  - Deploying

Vanilla:
  image: registry.gitlab.com/imagineteam1/web/imaginecraft:zip
  stage: CompressingVanilla
  script:
  - zip -r vanilla.zip packs/vanilla/*
  - ls
  cache:
    untracked: false
    policy: pull-push
    paths:
      - vanilla.zip
  only:
    - master

Modded:
  image: registry.gitlab.com/imagineteam1/web/imaginecraft:zip
  stage: CompressingModded
  script:
    - zip -r modded.zip packs/modded/*
    - ls
  cache:
    untracked: false
    policy: pull-push
    paths:
    - modded.zip
    - vanilla.zip
  only:
    - master

Win:
  image: registry.gitlab.com/imagineteam1/web/imaginecraft:node
  stage: Packing
  cache:
    untracked: false
    policy: pull-push
    paths:
      - imaginecraft/
      - vanilla.zip
      - modded.zip
  script:
      - git clone https://gitlab.com/imagineteam1/imaginecraft/
      - npm --prefix imaginecraft i
      - npm run --prefix imaginecraft package-win
      - ls
  only:
    - master

WinStall:
  image: registry.gitlab.com/imagineteam1/web/imaginecraft:mono
  stage: Packaging
  cache:
    untracked: false
    policy: pull-push
    paths:
      - ImagineCraft_Installer.exe
      - vanilla.zip
      - modded.zip
  script:
      - npm --prefix imaginecraft i
      - npm run --prefix imaginecraft create-installer-win
      - mv imaginecraft/release-builds/windows-installer/ImagineCraft_Installer.exe ImagineCraft_Installer.exe
      - ls
  only:
    - master

Pages:
  stage: Deploying
  cache:
    untracked: false
    policy: pull
  script:
    - ls
    - rm -rf packs
    - rm -rf imaginecraft
    - mkdir .public
    - cp -r * .public
    - mv .public public
    - ls
    - ls pub
  artifacts:
    paths:
      - public
  only:
    - master
