stages:
  - Zipping
  - Deploying
  - Stop

Modded:
  image: ubuntu:latest
  stage: Zipping
  tags:
    - docker
  script:
  - apt-get update -y && apt-get install -y zip
  - cd packs/modded/
  - zip -r modded.zip *
  - cd ../../.
  - mv packs/modded/modded.zip web/modded.zip
  only:
    - master

Deploy:
  image: docker/compose:latest
  tags:
    - docker
  stage: Deploying
  script:
    - docker-compose up -d --force-recreate --remove-orphans --build
  only:
   - master
  environment:
    name: Production
    url: https://cdn.imagine.team
    on_stop: Stop

Stop:
  image: docker/compose:latest
  tags:
    - docker
  stage: Stop
  script:
    - docker-compose down
  only: 
    - master
  environment:
    name: Production
    url: https://cdn.imagine.team
    action: stop
  when: manual
    